/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const DailyCheckIn = IDL.Record({
  'day' : IDL.Nat,
  'moodRating' : IDL.Opt(IDL.Nat),
  'reducedBehavior' : IDL.Bool,
  'notes' : IDL.Text,
  'taskCompleted' : IDL.Bool,
});
export const Pattern = IDL.Record({
  'patternType' : IDL.Text,
  'snippet' : IDL.Text,
  'confidenceScore' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Habit = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'action' : IDL.Text,
  'difficulty' : IDL.Int,
  'whenToCue' : IDL.Text,
  'rationale' : IDL.Text,
  'category' : IDL.Text,
});
export const DailyProgramEntry = IDL.Record({
  'day' : IDL.Nat,
  'explanation' : IDL.Text,
  'task' : Habit,
  'reflectionPrompt' : IDL.Opt(IDL.Text),
});
export const Program = IDL.Record({
  'days' : IDL.Vec(DailyProgramEntry),
  'checkIns' : IDL.Vec(DailyCheckIn),
});
export const OnlineActivityEntry = IDL.Record({
  'id' : IDL.Nat,
  'externalBlob' : IDL.Opt(ExternalBlob),
  'sourceLabel' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addActivityEntry' : IDL.Func(
      [
        IDL.Tuple(IDL.Int, IDL.Text, IDL.Text),
        IDL.Opt(IDL.Vec(IDL.Nat8)),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'addCheckIn' : IDL.Func([DailyCheckIn], [], []),
  'addPattern' : IDL.Func([Pattern], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProgram' : IDL.Func([Program], [], []),
  'getActivityEntries' : IDL.Func(
      [],
      [IDL.Vec(OnlineActivityEntry)],
      ['query'],
    ),
  'getActivityEntry' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(OnlineActivityEntry)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHabitLibrary' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
  'getPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
  'getProgram' : IDL.Func([], [IDL.Opt(Program)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedHabitLibrary' : IDL.Func([IDL.Vec(Habit)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const DailyCheckIn = IDL.Record({
    'day' : IDL.Nat,
    'moodRating' : IDL.Opt(IDL.Nat),
    'reducedBehavior' : IDL.Bool,
    'notes' : IDL.Text,
    'taskCompleted' : IDL.Bool,
  });
  const Pattern = IDL.Record({
    'patternType' : IDL.Text,
    'snippet' : IDL.Text,
    'confidenceScore' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Habit = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'action' : IDL.Text,
    'difficulty' : IDL.Int,
    'whenToCue' : IDL.Text,
    'rationale' : IDL.Text,
    'category' : IDL.Text,
  });
  const DailyProgramEntry = IDL.Record({
    'day' : IDL.Nat,
    'explanation' : IDL.Text,
    'task' : Habit,
    'reflectionPrompt' : IDL.Opt(IDL.Text),
  });
  const Program = IDL.Record({
    'days' : IDL.Vec(DailyProgramEntry),
    'checkIns' : IDL.Vec(DailyCheckIn),
  });
  const OnlineActivityEntry = IDL.Record({
    'id' : IDL.Nat,
    'externalBlob' : IDL.Opt(ExternalBlob),
    'sourceLabel' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addActivityEntry' : IDL.Func(
        [
          IDL.Tuple(IDL.Int, IDL.Text, IDL.Text),
          IDL.Opt(IDL.Vec(IDL.Nat8)),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'addCheckIn' : IDL.Func([DailyCheckIn], [], []),
    'addPattern' : IDL.Func([Pattern], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProgram' : IDL.Func([Program], [], []),
    'getActivityEntries' : IDL.Func(
        [],
        [IDL.Vec(OnlineActivityEntry)],
        ['query'],
      ),
    'getActivityEntry' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(OnlineActivityEntry)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHabitLibrary' : IDL.Func([], [IDL.Vec(Habit)], ['query']),
    'getPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
    'getProgram' : IDL.Func([], [IDL.Opt(Program)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedHabitLibrary' : IDL.Func([IDL.Vec(Habit)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };