/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyCheckIn {
  'day' : bigint,
  'moodRating' : [] | [bigint],
  'reducedBehavior' : boolean,
  'notes' : string,
  'taskCompleted' : boolean,
}
export interface DailyProgramEntry {
  'day' : bigint,
  'explanation' : string,
  'task' : Habit,
  'reflectionPrompt' : [] | [string],
}
export type ExternalBlob = Uint8Array;
export interface Habit {
  'id' : string,
  'duration' : bigint,
  'action' : string,
  'difficulty' : bigint,
  'whenToCue' : string,
  'rationale' : string,
  'category' : string,
}
export interface OnlineActivityEntry {
  'id' : bigint,
  'externalBlob' : [] | [ExternalBlob],
  'sourceLabel' : string,
  'notes' : string,
  'timestamp' : bigint,
  'image' : [] | [Uint8Array],
}
export interface Pattern {
  'patternType' : string,
  'snippet' : string,
  'confidenceScore' : bigint,
}
export interface Program {
  'days' : Array<DailyProgramEntry>,
  'checkIns' : Array<DailyCheckIn>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addActivityEntry' : ActorMethod<
    [[bigint, string, string], [] | [Uint8Array], [] | [ExternalBlob]],
    bigint
  >,
  'addCheckIn' : ActorMethod<[DailyCheckIn], undefined>,
  'addPattern' : ActorMethod<[Pattern], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProgram' : ActorMethod<[Program], undefined>,
  'getActivityEntries' : ActorMethod<[], Array<OnlineActivityEntry>>,
  'getActivityEntry' : ActorMethod<[bigint], [] | [OnlineActivityEntry]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHabitLibrary' : ActorMethod<[], Array<Habit>>,
  'getPatterns' : ActorMethod<[], Array<Pattern>>,
  'getProgram' : ActorMethod<[], [] | [Program]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedHabitLibrary' : ActorMethod<[Array<Habit>], undefined>,
  'updateFullProgram' : ActorMethod<
    [Array<DailyProgramEntry>, Array<DailyCheckIn>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];